keys:
  - &fugi BF37903AE6FD294C4C674EE24472A20091BFA792
  # machines
  - &librarian age1awp9cl63hldzmwkv88ry06hatea3aynshddfwcst36aa5a83k3eq807zu2
  - &nitwit age1mwtf0z96stqezcxgrrkt4zx5cnc2nekt06vpzz8m74tz68uy6y7shepulr
  - &shepherd age19f0hh85t7dm5rk3t9x3xghlnmp4z44hdsh0qhhsnenyl0f3pe9csg4a4w9
creation_rules:
  - path_regex: ^hosts/librarian/.*
    key_groups:
      - pgp:
        - *fugi
        age:
        - *librarian
  - path_regex: ^hosts/nitwit/.*
    key_groups:
      - pgp:
        - *fugi
        age:
        - *nitwit
  - path_regex: ^hosts/shepherd/.*
    key_groups:
      - pgp:
        - *fugi
        age:
        - *shepherd
