keys:
  - &fugi BF37903AE6FD294C4C674EE24472A20091BFA792
  # machines
  - &librarian age1awp9cl63hldzmwkv88ry06hatea3aynshddfwcst36aa5a83k3eq807zu2
creation_rules:
  - path_regex: ^hosts/librarian/secrets\.yaml$
    key_groups:
      - pgp:
        - *fugi
        age:
        - *librarian
