{ config, lib, ... }:
{
  imports = [
    ./helix.nix
    ./zsh.nix
  ];

  home.stateVersion = "25.11";
  home.username = "fugi";
  home.homeDirectory = "/home/users/fugi";

  home.file.".ssh/authorized_keys" = {
    text = ''
      # generated by home-manager
      ${lib.concatLines config.fugi.authorizedKeys}
    '';
    onChange = ''
      cp --remove-destination $(readlink ~/.ssh/authorized_keys) ~/.ssh/authorized_keys
    '';
    force = true;
  };

  programs.nh = {
    enable = true;
    flake = "$HOME/.config/home-manager";
  };
}
